### ISSUE TITLE
Cannot refresh repositories

### ISSUE THREAD

**Issue by Balethorn** [UnknownX7/DalamudRepoBrowser#11]
If u try to refresh the repository list, it empties it and stays blank.

I have checked the dalamud logs for errors, this ones always appears when trying to refresh:

--------------------------------
21:58:17.817 | INF [DalamudRepoBrowser] Fetching repositories from https://api.xivplugins.com/v1/dalamud/repos
--------------------------------
21:58:17.818 | ERR [DalamudRepoBrowser] Failed loading repositories from https://api.xivplugins.com/v1/dalamud/repos
System.ArgumentOutOfRangeException: Valid values are between -62135596800 and 253402300799, inclusive. (Parameter 'seconds')
   at System.DateTimeOffset.FromUnixTimeSeconds(Int64 seconds)
   at DalamudRepoBrowser.DalamudRepoBrowser.ShouldCheckRepoList() in D:\a\DalamudRepoBrowser\DalamudRepoBrowser\DalamudRepoBrowser.cs:line 238
   at DalamudRepoBrowser.DalamudRepoBrowser.<>c__DisplayClass43_0.<FetchRepoListAsync>b__0() in D:\a\DalamudRepoBrowser\DalamudRepoBrowser\DalamudRepoBrowser.cs:line 256

Already tried to reinstall the plugin, restart game, etc...
Dalamud version: 7.0.0.8 eb12fe8
Plugin ver: 2.0.3.0

**Comment by Balethorn** [comment]
It has resolved itself, I guess it was related to the xivplugins api.

**Comment by HimitsuYami** [comment]
I just encountered this issue myself last night

The only way I fixed it was uninstalling, deleting the plugin file and the config, and then reinstalling
