### ISSUE TITLE
base_repo.json files should be filtered out

### ISSUE THREAD

**Issue by bladehawkz** [UnknownX7/DalamudRepoBrowser#3]
There are various repos with both base_repo.json and repo.json files.

Usually the base_repo.json versions fail to install, and can break updates since 1.0.0.0 is higher than various other versions that currently exist, like Lmeter and Penumbra which use 0.x.x.x

Filtering out base_repo.json should fix this.

**Comment by kalilistic** [comment]
I'll fix this today at the API level. https://github.com/kalilistic/neat-plugins-plus/issues/7.

**Comment by kalilistic** [comment]
This should be all set now. Any updates should also use repo.json instead of base_repo.json.
