### ISSUE TITLE
raw.githubusercontent.com not being replaced by github.com repos neatly.

### ISSUE THREAD

**Issue by alsiniz** [UnknownX7/DalamudRepoBrowser#7]
If I replace an https://raw.githubusercontent.com repo with an https://github.com repo the plugins within that repo become orphaned with the error message "This plugin's source repository is no longer available." in the /xlplugins menu.

I was just trying to restore the check marks in the repo browser for the repos I already have added since the repositories in the browser changed to the https://github.com URLs not long ago.

Was getting this with your repository too. I've reverted back to the https://raw.githubusercontent.com URLs for the repositories for now, but I have no check marks for any repos in the repo browser now.

**Comment by kalilistic** [comment]
There was a one-time change in the API to use the cleaner /raw/ urls. The message "This plugin's source repository is no longer available." should go-away once you've restarted the game.
