### ISSUE TITLE
Ping shooting up to ~1k as repos load

### ISSUE THREAD

**Issue by Electrized** [UnknownX7/DalamudRepoBrowser#9]
/xlrepos completely takes over my internet connection as it loads all the repos, admittedly with the upside that repository loading is much faster now

Not sure if intended, but thought i'd point this out incase its not intended behavior :p

**Comment by Lemagex** [comment]
For me, it pushes the ping up high for too long and the game times out and boots me before i can make use of the repos.

**Comment by ghost** [comment]
just tried opening the browser today and wow it freezes everything. i had to disable it :(

**Comment by 720mmHowizter** [comment]
for me it makes the game run at <1fps, even the audio sounds like 0.2x speed down

**Comment by Lemagex** [comment]
May possibly be a memory leak? I ran a check while using it to test, my ram usage goes from 5gb to 89gb (128gb system) when it loads repos...
